language: php
php:
  - nightly
sudo: true
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
before_install:
  - sudo add-apt-repository ppa:curse-sds/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libxdiff-dev libxdiff0
install:
  - phpize
  - EXTRA_LDFLAGS="-precious-files-regex .libs/xdiff.gcno" LDFLAGS="-lgcov" CFLAGS="-Wall -fno-strict-aliasing -coverage -O0" ./configure
  - make all
script:
  - TEST_PHP_EXECUTABLE=$(which php) php -n
    -d open_basedir= -d output_buffering=0 -d memory_limit=-1
    run-tests.php -n
    -d extension_dir=modules -d extension=xdiff.so --show-diff
    tests
  - gcov --object-directory .libs *.c
  - bash <(curl -s https://codecov.io/bash)
