language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - REPORT_EXIT_STATUS=1 TESTS="-q --show-diff" TEST_PHP_EXECUTABLE=php

before_script:
  - sudo -E bash tests/bootstrap.sh

install:
  - phpize
  - sh tests/patch-Makefile_global.sh
  - ./configure
  - make

script: make test

notifications:
  email:
    - gasol.wu+travis@gmail.com
