mkdir -p ext/date/tests
mkdir -p ext/simplexml/tests
mkdir -p ext/pdo_pgsql/tests
mkdir -p ext/json/tests
mkdir -p ext/tokenizer/tests
mkdir -p ext/shmop/tests
mkdir -p ext/wddx/tests
mkdir -p ext/sybase_ct/tests
mkdir -p ext/dba/tests
mkdir -p ext/pspell/tests
mkdir -p ext/pdo_odbc/tests
mkdir -p ext/mysqli/tests
mkdir -p ext/sqlite3/tests
mkdir -p ext/tidy/tests
mkdir -p ext/sysvsem/tests
mkdir -p ext/sqlite/tests
mkdir -p ext/sqlite/tests/pdo
mkdir -p ext/curl/tests
mkdir -p ext/sysvmsg/tests
mkdir -p ext/pdo_firebird/tests
mkdir -p ext/bcmath/tests
mkdir -p ext/phar/tests
mkdir -p ext/phar/tests/cache_list
mkdir -p ext/phar/tests/zip
mkdir -p ext/phar/tests/tar
mkdir -p ext/fileinfo/tests
mkdir -p ext/mysql/tests
mkdir -p ext/exif/tests
mkdir -p ext/spl/examples/tests
mkdir -p ext/spl/tests
mkdir -p ext/pcre/tests
mkdir -p ext/soap/tests
mkdir -p ext/soap/tests/soap12
mkdir -p ext/soap/tests/interop/Round3/GroupD
mkdir -p ext/soap/tests/interop/Round3/GroupE
mkdir -p ext/soap/tests/interop/Round3/GroupF
mkdir -p ext/soap/tests/interop/Round4/GroupI
mkdir -p ext/soap/tests/interop/Round4/GroupH
mkdir -p ext/soap/tests/interop/Round2/GroupB
mkdir -p ext/soap/tests/interop/Round2/Base
mkdir -p ext/soap/tests/schema
mkdir -p ext/soap/tests/bugs
mkdir -p ext/calendar/tests
mkdir -p ext/ftp/tests
mkdir -p ext/pdo_mysql/tests
mkdir -p ext/ctype/tests
mkdir -p ext/mbstring/tests
mkdir -p ext/libxml/tests
mkdir -p ext/ldap/tests
mkdir -p ext/reflection/tests
mkdir -p ext/enchant/tests
mkdir -p ext/xmlreader/tests
mkdir -p ext/standard/tests/filters
mkdir -p ext/standard/tests/versioning
mkdir -p ext/standard/tests/serialize
mkdir -p ext/standard/tests/general_functions
mkdir -p ext/standard/tests/assert
mkdir -p ext/standard/tests/url
mkdir -p ext/standard/tests/streams
mkdir -p ext/standard/tests/array
mkdir -p ext/standard/tests/mail
mkdir -p ext/standard/tests/class_object
mkdir -p ext/standard/tests/file
mkdir -p ext/standard/tests/directory
mkdir -p ext/standard/tests/time
mkdir -p ext/standard/tests/math
mkdir -p ext/standard/tests/image
mkdir -p ext/standard/tests/dir
mkdir -p ext/standard/tests/misc
mkdir -p ext/standard/tests/strings
mkdir -p ext/standard/tests/network
mkdir -p ext/pcntl/tests
mkdir -p ext/imap/tests
mkdir -p ext/gmp/tests
mkdir -p ext/sockets/tests
mkdir -p ext/session/tests
mkdir -p ext/hash/tests
mkdir -p ext/posix/tests
mkdir -p ext/bz2/tests
mkdir -p ext/zip/tests
mkdir -p ext/mcrypt/tests
mkdir -p ext/pdo_sqlite/tests
mkdir -p ext/sysvshm/tests
mkdir -p ext/com_dotnet/tests
mkdir -p ext/iconv/tests
mkdir -p ext/xml/tests
mkdir -p ext/zlib/tests
mkdir -p ext/xmlrpc/tests
mkdir -p ext/dom/tests
mkdir -p ext/xsl/tests
mkdir -p ext/readline/tests
mkdir -p ext/pgsql/tests
mkdir -p ext/gd/tests
mkdir -p ext/intl/tests
mkdir -p ext/pdo/tests
mkdir -p ext/pdo_oci/tests
mkdir -p ext/gettext/tests
mkdir -p ext/openssl/tests
mkdir -p ext/ereg/tests
mkdir -p ext/oci8/tests
mkdir -p ext/filter/tests
mkdir -p ext/interbase/tests
mkdir -p ext/skeleton/tests
mkdir -p ext/xmlwriter/tests
mkdir -p Zend/tests
mkdir -p Zend/tests/multibyte
mkdir -p Zend/tests/constants
mkdir -p tests/lang
mkdir -p tests/output
mkdir -p tests/security
mkdir -p tests/func
mkdir -p tests/basic
mkdir -p tests/run-test
mkdir -p tests/strings
mkdir -p tests/classes
mkdir -p sapi/cli/tests
mkdir -p sapi/tests
mkdir -p sapi/cgi/tests